name: daily-scrape

on:
  schedule:
    - cron: "0 8 * * *"  # 8:00 AM UTC daily (adjust timezone as needed)
  workflow_dispatch:
  push:
    branches:
      - revamp/ai-cyber-scraper
      - main

permissions:
  contents: write
  discussions: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Scrape AI
        env:
          USAJOBS_EMAIL: ${{ secrets.USAJOBS_EMAIL }}
          USAJOBS_API_KEY: ${{ secrets.USAJOBS_API_KEY }}
        run: python -m ai_cyberjobs.cli scrape --category ai

      - name: Scrape Cyber
        env:
          USAJOBS_EMAIL: ${{ secrets.USAJOBS_EMAIL }}
          USAJOBS_API_KEY: ${{ secrets.USAJOBS_API_KEY }}
        run: python -m ai_cyberjobs.cli scrape --category cyber

      - name: Build site data
        run: python -m ai_cyberjobs.cli build-site

      - name: Detect changes
        id: changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit & push data/site updates
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore(data): update job feeds $(date -u +'%Y-%m-%d')"
          git push

      - name: Send detailed Discord notifications
        if: steps.changes.outputs.changed == 'true'
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: python -m ai_cyberjobs.cli send-detailed-discord

      - name: Send summary notifications
        if: steps.changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCUSSION_CATEGORY_ID: ${{ secrets.DISCUSSION_CATEGORY_ID }}
        run: python -m ai_cyberjobs.cli send-notifications --site-url auto

      - name: Post detailed Discussion (full listings)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCUSSION_CATEGORY_ID: ${{ secrets.DISCUSSION_CATEGORY_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "Posting detailed discussion with category $DISCUSSION_CATEGORY_ID"
          python -m ai_cyberjobs.cli post-discussion-detailed --max-jobs-per-category 10 --site-url auto

      # === Optional: Keep SMTP email (can be removed if not needed) ===
      - name: Render email bodies (no send)
        if: steps.changes.outputs.changed == 'true'
        run: |
          python -m ai_cyberjobs.cli notify --category both --no-send --output-dir out/emails
          ls -la out/emails || true

      - name: Set email subjects
        if: steps.changes.outputs.changed == 'true'
        run: |
          # Defaults without counts
          echo "AI_SUBJECT=New AI Jobs – USAJOBS" >> $GITHUB_ENV
          echo "CYBER_SUBJECT=New Cybersecurity Jobs – USAJOBS" >> $GITHUB_ENV
          # If meta files exist, extract computed subjects with counts
          if [ -f out/emails/ai.meta.json ]; then
            AI_SUBJ=$(python - <<'PY'
                import json
                print(json.load(open('out/emails/ai.meta.json'))['subject'])
                PY
                )
                            echo "AI_SUBJECT=$AI_SUBJ" >> $GITHUB_ENV
                        fi
                        if [ -f out/emails/cyber.meta.json ]; then
                            CY_SUBJ=$(python - <<'PY'
                import json
                print(json.load(open('out/emails/cyber.meta.json'))['subject'])
                PY
                )
                            echo "CYBER_SUBJECT=$CY_SUBJ" >> $GITHUB_ENV
                        fi

      # === Email via SMTP action (works with Office365 or Gmail via secrets) ===
      - name: Send AI email
        if: hashFiles('out/emails/ai.html') != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ${{ env.AI_SUBJECT }}
          to: jdoner@ewu.edu, ssteiner@ewu.edu
          from: ${{ secrets.EMAIL_FROM }}
          html_body: file://out/emails/ai.html
          ignore_cert: true

      - name: Send Cyber email
        if: hashFiles('out/emails/cyber.html') != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ${{ env.CYBER_SUBJECT }}
          to: jdoner@ewu.edu, ssteiner@ewu.edu
          from: ${{ secrets.EMAIL_FROM }}
          html_body: file://out/emails/cyber.html
          ignore_cert: true
